version: '3.8'

services:
  # Base de datos
  db:
    image: postgres:14
    container_name: project_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "5432:5432"

  # Backend (Node.js)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: project_backend
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydatabase
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app_network
    depends_on:
      - db
    ports:
      - "5000:5000"
  
  # Frontend (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: project_frontend
    environment:
      REACT_APP_API_URL: http://localhost/api
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app_network
    ports:
      - "3000:3000"
    depends_on:
      - backend

  # NGINX (Proxy)
  nginx:
    image: nginx:latest
    container_name: project_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
